### PR TITLE
remove question mark hack

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cowlicks** [comment]
@cpcloud  this isn't working and I'm not sure I understand exactly how it is supposed to. Can you take a look at the travis-ci failures?

**Comment by cpcloud** [comment]
I'm not handling the `'/'` character. I can get to this this evening.

**Comment by cowlicks** [comment]
@cpcloud I was able to get something nicer working based off this. Thanks!

**Comment by cpcloud** [comment]
cool

**Comment by cpcloud** [comment]
sorry about the delay

**Pull request closed without merging**
